/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.proutechos.sandbox.radiolivealacarte.server;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class EntryPointTest {
    @Test void appHasAGreeting() {
        EntryPoint classUnderTest = new EntryPoint();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

}
